export const strings = {
   en: {
      invoices: 'Invoices',
      newInvoice: 'New Invoice',
      noInvoices: 'No invoices',
      billFrom: 'Bill From',
      billTo: 'Bill To',
      itemList: 'Item List',
      addNewItem: 'Add New Item',
      discard: 'Discard',
      saveDraft: 'Save as Draft',
      saveSend: 'Save & Send',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      filter: 'Filter by status',
      nothingHere: 'There is nothing here',
      creteByClick: 'Create invoice by clicking New Invoice button and get started',
      form: {
         street: 'Street Address',
         city: 'City',
         postCode: 'Post Code',
         country: 'Country',
         client: `Client's Name`,
         clientEmail: `Client's Email`,
         invoiceDate: 'Invoice Date',
         paymentTerms: 'Payment Terms',
      },
   },
   rs: {
      invoices: 'Fakture',
      newInvoice: 'Nova Faktura',
      noInvoices: 'Nema faktura',
      billFrom: 'Račun od',
      billTo: 'Račun za',
      itemList: 'Lista proizvoda',
      addNewItem: 'Dodaj novi proizvod',
      discard: 'Odbaci',
      saveDraft: 'Sačuvaj kao nacrt',
      saveSend: 'Snimi i pošalji',
      saveChanges: 'Sačuvaj promene',
      cancel: 'Otkazati',
      filter: 'Filtriraj',
      nothingHere: 'Ovde nema ničega',
      creteByClick: 'Create invoice by clicking New Invoice button and get started',
      form: {
         street: 'Ulica',
         city: 'Grad',
         postCode: 'Poštanski broj',
         country: 'Država',
         client: 'Ime klijenta',
         clientEmail: 'Email klijenta',
         invoiceDate: 'Datum fakture',
         paymentTerms: 'Uslovi Plaćanja',
      },
   },
}
