export const strings = {
   en: {
      invoices: 'Invoices',
      newInvoice: 'New Invoice',
      noInvoices: 'No invoices',
      billFrom: 'Bill From',
      filter: 'Filter by status',
      form: {
         street: 'Street Address',
         city: 'City',
         postCode: 'Post Code',
         country: 'Country',
         client: `Client's Name`,
         clientEmail: `Client's Email`,
         invoiceDate: 'Invoice Date',
         paymentTerms: 'Payment Terms',
      },
   },
   rs: {
      invoices: 'Fakture',
      newInvoice: 'Nova Faktura',
      noInvoices: 'Nema faktura',
      billFrom: 'Račun od',
      filter: 'Filtriraj',
      form: {
         street: 'Ulica',
         city: 'Grad',
         postCode: 'Poštanski broj',
         country: 'Država',
         client: 'Ime klijenta',
         clientEmail: 'Email klijenta',
         invoiceDate: 'Datum fakture',
         paymentTerms: 'Uslovi Plaćanja',
      },
   },
}
